// Code generated by "jade.go"; DO NOT EDIT.

package imp

import (
	"io"

	"github.com/Joker/hpp"
	"github.com/Joker/jade/testdata/imp/model"
)

type Test struct {
	test string
}

func (t *Test) Simple(u *model.User, st []model.Story, w io.Writer) {

	r, wr := io.Pipe()
	go func() {
		buffer := &WriterAsBuffer{wr}

		buffer.WriteString(`<html><body><h1>`)
		WriteEscString(u.FirstName, buffer)
		buffer.WriteString(`</h1><p>Here's a list of your favorite colors:</p><ul>`)

		for _, colorName := range u.FavoriteColors {
			buffer.WriteString(`<li>`)
			WriteEscString(colorName, buffer)
			buffer.WriteString(`</li>`)
		}
		buffer.WriteString(`</ul><ul>`)

		for _, story := range st {
			buffer.WriteString(`<li>`)
			WriteInt(int64(story.StoryId), buffer)
			buffer.WriteString(`</li><li>`)
			WriteInt(int64(story.UserId), buffer)
			buffer.WriteString(`</li><li>`)
			WriteEscString(story.UserName, buffer)
			buffer.WriteString(`</li>`)
		}
		buffer.WriteString(`</ul></body></html>`)

		w.Close()
	}()
	hpp.Format(r, w)
}
