// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"html"
	"io"
	"strconv"

	"github.com/Joker/hpp"
	"github.com/Joker/jade/testdata/imp/model"
)

type Test struct {
	test string
}

func Simple(u *model.User, st []model.Story, wr io.Writer) {
	r, w := io.Pipe()
	go func() {
		buffer := &WriterAsBuffer{w}

		buffer.WriteString(`<html><body><h1>`)
		buffer.WriteString(html.EscapeString(u.FirstName))
		buffer.WriteString(`</h1><p>Here's a list of your favorite colors:</p><ul>`)

		for _, colorName := range u.FavoriteColors {
			buffer.WriteString(`<li>`)
			buffer.WriteString(html.EscapeString(colorName))
			buffer.WriteString(`</li>`)
		}
		buffer.WriteString(`</ul><ul>`)

		for _, story := range st {
			buffer.WriteString(`<li>`)
			buffer.WriteString(html.EscapeString(strconv.FormatInt(int64(story.StoryId), 10)))
			buffer.WriteString(`</li><li>`)
			buffer.WriteString(html.EscapeString(strconv.FormatInt(int64(story.UserId), 10)))
			buffer.WriteString(`</li><li>`)
			buffer.WriteString(html.EscapeString(story.UserName))
			buffer.WriteString(`</li>`)
		}
		buffer.WriteString(`</ul></body></html>`)

		w.Close()
	}()
	hpp.Format(r, wr)
}
